### ISSUE TITLE
Sparkoscope on Yarn

### ISSUE THREAD

**Issue by liambll** [ibm-research-ireland/sparkoscope#18]
Hi @YiannisGkoufas,

Another open question. I am wondering if Sparkoscope works with Yarn as well?
- When I submit a spark job to a Spark master (--master spark://masterIP:7077), I can view modified UI with resource usage metrics.
- When I submit a spark job to yarn (--master yarn), I can't find the modified UI.

May be I did something wrong.

**Comment by YiannisGkoufas** [comment]
Haven't tested it on yarn so I am not surprised it doesn't work.
Another item on my TODO list :)

**Comment by liambll** [comment]
Great :) I will try it out once it is available.

**Comment by YiannisGkoufas** [comment]
I tried it out and it seems to be working without a problem when plotting finished jobs.
Indeed the realtime plots are not visible, although they are published correctly in the MQTT topic.
I have to do a workaround to plug-in the realtime UI for yarn as well.
So the configuration for sparkoscope+yarn that works for me:

**metrics.properties**
```
executor.sink.hdfs.class=org.apache.spark.metrics.sink.HDFSSink
executor.sink.hdfs.pollPeriod = 1
executor.sink.hdfs.dir = file:///tmp/custom-metrics
executor.sink.hdfs.unit = seconds
```
(make sure to create the folder /tmp/custom-metrics)

**spark-defaults.conf**
```
spark.eventLog.enabled                  true
spark.eventLog.dir file:///tmp/spark-events
spark.history.fs.logDirectory file:///tmp/spark-events
spark.hdfs.metrics.dir           file:///tmp/custom-metrics
spark.yarn.historyServer.address        localhost:18080
```
(make sure to create the folder /tmp/spark-events)

Assuming that you have yarn running start Spark's History Server:
```
sbin/start-history-server.sh
```
Launch a job using yarn:
```
./bin/spark-submit --class org.apache.spark.examples.SparkPi     --master yarn     --deploy-mode cluster     --driver-memory 4g     --executor-memory 2g     --executor-cores 1     examples/jars/spark-examples*.jar     10000
```
After the application is done, you should be able to find it in the history server (localhost:18080) and also plot the metrics gathered.
In a clustered setup of course, you would have to substitute the /tmp directories with directories in the HDFS.
Let me know if it works for you as well.

**Comment by liambll** [comment]
Thanks, @YiannisGkoufas .
May I check what is the cluster configuration you use to to run Sparkoscope 2.1 on Yarn (Cloudera/Hortonwork, Java version, container setting, etc)?

On a single node Hadoop Spark cluster on my PC (Java7, Hadoop2.7.2, Sparkoscope 2.1.0):
- With `executor.source.jvm.class=org.apache.spark.metrics.source.SigarSource` in metrics.properties:
  - Running with Spark standalone `spark-shell --master spark://host:7077` works fine, I can see all metrics
  - Running with Yarn `spark-shell --master yarn`, I keep getting below error. Increasing the container memory and setting executor memory does not seem to solve the problem.
> WARN cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Container marked as failed: container_1503100328375_0003_02_000003 on host: liam. Exit status: 1. Diagnostics: Exception from container-launch.
> Container id: container_1503100328375_0003_02_000003
> Exit code: 1

- Without `executor.source.jvm.class=org.apache.spark.metrics.source.SigarSource`:
Running with Spark standalone and Yarn both works fine except I don't see cpu/memory usages in UI (obviously) -> That means what you mentioned above should work if I can get SigarSource to work with Yarn on my PC.

So, I'm guessing I might have done something wrong with SigarSource

On a 4-nodes Cloudera cluster, the metrics are not shown at all (the dropdown list on modified UI is blank when I tried running in Spark standalone mode), but this is probably something to do with my configuration.

**Comment by YiannisGkoufas** [comment]
Hi Liam,

so what I described above was tried on my laptop.
Downloaded https://github.com/ibm-research-ireland/sparkoscope/releases/download/v2.1.0/spark-2.1.0-bin-sparkoscope.tgz, modified the configuration files as above and tried the SparkPi.
Regarding SigarSource have you followed all the steps described here https://github.com/ibm-research-ireland/sparkoscope#installationconfiguration ( Configure Sigar metrics source ) ?
So from what you described, SigarSource works fine for you in Standalone Mode but not in Yarn mode correct?
Regarding Cloudera, I haven't tried it there to be honest. Just a shot in the dark: is it possible that you run a very quick job and it didn't have time to capture any metrics at all? As a debugging step can you please check that the directory you specified in executor.sink.hdfs.dir has data inside it for each application?
Thanks!

**Comment by liambll** [comment]
I actually simply run `spark-shell --master yarn` or  `spark-shell --master spark://masterIP:7077` to keep the session running. 
Yes, I have followed all the step to configure SigarSource. It works fine in Spark Standalone Mode. However, in Yarn mode, it seems the container couldn't be initialised with SigarSource. So, I am guessing there is something wrong with my yarn configuration.

On my Cloudera cluster, I can see that in HDFS (namenode is `PHEMI`:
```
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://PHEMI</value>
  </property>
```
)
- there are log files created in `hdfs://PHEMI/spark-logs`
- there is no metrics json file created in `hdfs://PHEMI/custom-metrics`

I already changed the configuration to point to HDFS location 

**metrics.properties:**
```
executor.sink.hdfs.class=org.apache.spark.metrics.sink.HDFSSink
executor.sink.hdfs.pollPeriod = 20
executor.sink.hdfs.dir = hdfs://PHEMI/custom-metrics
executor.sink.hdfs.unit = seconds

executor.sink.mqtt.class=org.apache.spark.metrics.sink.MQTTSink
executor.sink.mqtt.pollPeriod = 1
executor.sink.mqtt.host = mgr2.thrift.phemi.com
executor.sink.mqtt.port = 1883
executor.sink.mqtt.unit = seconds

executor.source.jvm.class=org.apache.spark.metrics.source.SigarSource
```
**spark-default:**
```
spark.moquette.port 1883
spark.moquette.websocket_port 8888
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://PHEMI/spark-logs
spark.history.fs.logDirectory    hdfs://PHEMI/spark-logs
spark.hdfs.metrics.dir           hdfs://PHEMI/custom-metrics
```
**Spark-env.sh:**
```
HADOOP_CONF_DIR=/opt/phemi/dstk/phemi/hdp/hadoop/conf
LD_LIBRARY_PATH=/home/opc/hyperic-sigar-1.6.4/sigar-bin/lib/:$LD_LIBRARY_PATH
```

**Comment by YiannisGkoufas** [comment]
Hi Liam,
I updated the instructions for Sparkoscope on yarn and I will create 2 separate issues about realtime plots on yarn and instructions for the cloudera distribution
