### ISSUE TITLE
Is the metrics collected specific for each job that I run (job meaning a jar (application) to submit, not jobs with in one application) ? i.e. if I am running multiple jobs simultaneously, cpu or RAM usage accounts for all the jobs or I can have metrics for each job run?

### ISSUE THREAD

**Issue by filmonhg** [ibm-research-ireland/sparkoscope#6]

**Comment by YiannisGkoufas** [comment]
Hi @filmonhg sorry for the late response. You will have metrics for each job submitted. But beware that the metrics reported represent the state of the node/vm in which each worker is running. It is not captured the RAM/CPU consumed from the specific job.
