### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by Mehrab-Tanjim** [ibm-research-ireland/sparkoscope#8]
I have successfully run spark pi example in sparkoscope and I can see all the custom metrics in the UI.
But for my own spark application which I have written in java for spark 2.0.0 is showing an error. 
I later built my application for spark 2.1.0 yet same error is thrown. I am not sure what is wrong (my application can successfully complete, only I cant see all the custom metrics in the UI).
I have attached the screenshot of the error below:

![error](https://cloud.githubusercontent.com/assets/7347897/24058436/453d87c8-0b75-11e7-89f0-024a9d7af1c5.png)

**Comment by YiannisGkoufas** [comment]
Hi, so I didn't manage to recreate the issue on my setup.
Can you send me the spark-defaults.conf and metrics.properties files to have a look?
Are the metrics stored successfully on HDFS?

**Comment by Mehrab-Tanjim** [comment]
It was solved later, mostly probably machine issues, sorry for late reply.
